version: '3.8'

services:

  mysql1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307


volumes:
  mysql1: