version: '3.9'

services:

  mongo1:
    image: mongo:4.4.4
    container_name: mongo1
    restart: on-failure
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "30001" ]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 30s
      start_period: 5s
    networks:
      - net


  mongo2:
    image: mongo:4.4.4
    container_name: mongo2
    restart: on-failure
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "30002" ]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30002:30002
    networks:
      - net

  mongo3:
    container_name: mongo3
    image: mongo:4.4.4
    restart: on-failure
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "30003" ]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 30003:30003
    networks:
      - net



  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    container_name: app
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net:


#use: docker-compose up -d --build