server:
  port: 8102

spring:
  application:
    name: doctors-service

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
